### ISSUE TITLE
[feature req] python3 compat

### ISSUE THREAD

**Issue by AlJohri** [matalo33/py_oathtool#6]
```
Traceback (most recent call last):
  File "/Users/johria/.pyenv/versions/3.6.5/bin/otp", line 7, in <module>
    from py_oathtool.otp import main
  File "/Users/johria/.pyenv/versions/3.6.5/lib/python3.6/site-packages/py_oathtool/otp.py", line 78
    except yaml.YAMLError, err:
                         ^
SyntaxError: invalid syntax
```

**Comment by matalo33** [comment]
Thanks for the detailed bug report. Feel free to implement this and submit a pull request.
